features/gsaudit/urls.py

def refine_get_urls(original):

    def get_urls():
        from django.conf.urls.defaults import url, patterns, include
        urlpatterns = patterns('gsaudit.views',
            url(r'^$', 'dashboard.index'),
            url(r'^myaccount/$', 'dashboard.myaccount', name='myaccount'),
            url(r'^course/(?P<grade_id>\d+)_(?P<subject_id>\d+)/$', 'course.index', name='course-index'),
            url(r'^course/overview/(?P<grade_id>\d+)_(?P<subject_id>\d+)/$', 'course.overview', name='course-overview'),
            url(r'^course/subject_statistics/(?P<grade_id>\d+)_(?P<subject_id>\d+)/$', 'course.subject_statistics', name='course-subject_statistics'),
             url(r'^course/(?P<grade_id>\d+)_(?P<subject_id>\d+)/pupil/(?P<pupil_id>\d+)/$', 'course.pupil_frame', name='course-pupil_frame'),

            url(r'^pupil/profile/(?P<pupil_id>\d+)/$', 'pupil.profile', name='pupil-profile'),
            url(r'^pupil/ta_info/(?P<pupil_id>\d+)/(?P<subject_id>\d+)/(?P<grade_id>\d+)/$', 'pupil.pupil_ta_info', name='pupil-ta_info'),
            url(r'^pupil/eval_info/(?P<pupil_id>\d+)/(?P<subject_id>\d+)/(?P<grade_id>\d+)/$', 'pupil.pupil_eval_info', name='pupil-eval_info'),
            url(r'^pupil/statistic/(?P<grade_id>\d+)_(?P<subject_id>\d+)/pupil/(?P<pupil_id>\d+)/$', 'pupil.pupil_statistic', name='pupil-statistic'),
            url(r'^pupil/print_statistic/(?P<grade_id>\d+)_(?P<subject_id>\d+)/pupil/(?P<pupil_id>\d+)/$', 'pupil.print_pupil_statistic', name='pupil-print_statistic'),
          
        
            
            url(r'^audit/evaluate/(?P<audit_id>\d+)/$', 'audit.evaluate', name='audit-evaluate'),
            url(r'^audit/manage/course/(?P<grade_id>\d+)_(?P<subject_id>\d+)/$', 'audit.manage', name='audit-manage'),
            url(r'^audit/manage/(?P<audit_id>\d+)/course/(?P<grade_id>\d+)_(?P<subject_id>\d+)/$', 'audit.manage', name='audit-manage'),
            url(r'^audit/listing/course/(?P<grade_id>\d+)_(?P<subject_id>\d+)/$', 'audit.listing', name='audit-listing'),
            url(r'^audit/calendar_listing/course/(?P<grade_id>\d+)_(?P<subject_id>\d+)/$', 'audit.calendar_listing', name='audit-calendar_listing'),
            url(r'^audit/delete/(?P<audit_id>\d+)/$', 'audit.delete', name='audit-delete'),

            url(r'^exam/manage/course/(?P<grade_id>\d+)_(?P<subject_id>\d+)/$', 'audit.manage', {'written_exam': True}, name='exam-manage'),
            url(r'^exam/manage/(?P<audit_id>\d+)/course/(?P<grade_id>\d+)_(?P<subject_id>\d+)/$', 'audit.manage', {'written_exam': True}, name='exam-manage'),
            # direct_to_template was removed in django 1.5
            #url(r'^about/$', direct_to_template, {'template': 'gsaudit/about.html'}, name='about'),
        )
        
        from users import authurls
        from gsaudit.models import Teacher
        urlpatterns += authurls.get_patterns(Teacher)
        return urlpatterns + original()
    return get_urls




features/gsaudit/models.py
# -*- coding: UTF-8 -*-
from django.db import models
from users.models import AbstractUser
import mptt
import users
from mptt.fields import TreeForeignKey
from jsonfield import JSONField
from django.utils.safestring import mark_safe
from django.utils.html import escape
from django.conf import settings

GENDER_CHOICES = (('W', 'weiblich',),('M', 'männlich',))


class BaseModel(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    jsondata = JSONField(editable=False, default={})
    
    class Meta:
        abstract = True


class School(BaseModel):
    name = models.CharField(max_length=255)
    domain = models.CharField(max_length=200)
    address = models.TextField()
    contact_person = models.TextField()
    
    class Meta:
        verbose_name = 'Schule'
        verbose_name_plural = 'Schulen'
        
    def get_grades(self):
        ''' Retrieves all grades of this school '''
        return Grade.objects.select_related().filter(school=self)
    
    def get_teachers(self):
        ''' Retrieves all teachers of this school '''
        return Teacher.objects.select_related().filter(school=self)
    
    def get_pupils(self):
        return Pupil.objects.filter(school=self)
    
    def get_teaching_assignments(self):
        return TeachingAssignment.objects.filter(grade__school=self)
    
    def __unicode__(self):
        return '%s' % (self.name)


class Teacher(AbstractUser):
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, verbose_name='Geschlecht')
    phone = models.CharField(max_length=255, null=True, blank=True, verbose_name='Telefon')
    school = models.ForeignKey(School, verbose_name='Schule')

    class Meta:
        verbose_name = 'LehrerIn'
        verbose_name_plural = 'LehrerInnen'

    def get_gender(self):
        ''' Retrieves gender of this teacher '''
        return 'Herr' if (self.gender=='M') else 'Frau';
    
    def get_grades(self):
        ''' Retrieves all grades the teacher is teaching in '''
        return Grade.objects.filter(teachingassignment__teacher=self).distinct()
    
    def get_subjects(self):
        ''' Retrieves all subjects the teacher is teaching for '''
        return Subject.objects.filter(teachingassignment__teacher=self)
    
    def get_grade_subjects(self, grade):
        ''' Retrieves all subjects the teacher is teaching for the given grade '''
        return Subject.objects.filter(teachingassignment__teacher=self, teachingassignment__grade=grade)
    

    def __unicode__(self):
        return '%s %s %s' % (self.get_gender(), self.first_name, self.last_name)        

    def get_salutation(self):
        return '%s %s' % (self.first_name, self.last_name)
        
    def full_salutation(self):
        s = ''
        if self.gender == 'W':
            s+= 'Frau '
        else:
            s+= 'Herr '
        return s + self.get_salutation()

users.register(Teacher,dict(
    APP_LABEL = 'gsaudit',
    URL_PREFIX = 'teachers',
    FROM_EMAIL = settings.DEFAULT_FROM_EMAIL,
    #LOGIN_URL = '/teachers/login/',
    CONFIRM_EMAIL_SUBJECT = 'Ihr Zugang für GS-Kompetenzen',
    #LOGIN_REDIRECT_URL = '/',
    #LOGOUT_REDIRECT_URL = '/teachers/login/',
    USE_USER_EMAIL = True,
    ADDITIONALLY_SEND_TO = [],
))        

class Grade(BaseModel):
    name = models.CharField(max_length=255)
    school = models.ForeignKey(School, verbose_name='Schule')
    pupils = models.ManyToManyField('Pupil', through='GradeParticipant', null=True, blank=True)

    class Meta:
        verbose_name = 'Klasse'
        verbose_name_plural = 'Klassen'
    
    def get_all_subjects(self):
        ''' Retrieves all subjects of this grade '''
        return Subject.objects.filter(teachingassignment__grade=self)
    
    def get_all_teachers(self):
        ''' Retrieves all teachers of this grade '''
        return Teacher.objects.filter(teachingassignment__grade=self)
    
    def get_subject_teacher(self, subject):
        ''' Retrieves the teacher for the given subjects in this grade '''
        return Teacher.objects.get(teachingassignment__grade=self, teachingassignment__subject=subject)
    
    def get_teacher_subjects(self, teacher):
        ''' Retrieves all subjects of the given teacher in this grade '''
        return Subject.objects.filter(teachingassignment__grade=self, teachingassignment__teacher=teacher)
        
    def get_participants(self):
        ''' Retrieves all participants in this grade '''
        return Pupil.objects.filter(gradeparticipant__grade=self).order_by('last_name')
    
    def __unicode__(self):
        return self.name


class Pupil(BaseModel):
    first_name = models.CharField(max_length=255, verbose_name='Vorname')
    last_name = models.CharField(max_length=255, verbose_name='Nachname')
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, verbose_name='Geschlecht')
    birthday = models.DateField(verbose_name='Geburtsdatum', blank=True, null=True)
    note = models.TextField(null=True, blank=True, verbose_name='Notiz')
    school = models.ForeignKey(School, verbose_name='Schule')

    class Meta:
        verbose_name = 'SchülerIn'
        verbose_name_plural = 'SchülerInnen'
        ordering = ('last_name', 'first_name')

    def gradeparticipant_vis(self):
        return ' '.join([unicode(x) for x in self.gradeparticipant_set.all()])

    def get_full_name(self):
        return self.first_name + ' ' + self.last_name

    def get_all_grades(self):
        ''' Retrieves all grades in which this pupil is participating '''
        return Grade.objects.filter(gradeparticipant__pupil=self)

    def get_all_subjects(self):
        ''' Retrieves all subjects in which this pupil is participating '''
        subjects = []
        for grade in self.get_all_grades():
            subjects += grade.get_all_subjects()
            
        return subjects;

    def get_grade_subjects(self, grade_id):
        ''' Retrieves all subjects for the given in which this pupil is participating '''
        return Grade.objects.get(id=grade_id).get_all_subjects()

    def get_grade_subject_teacher(self, grade_id, subject_id):
        ''' Retrieves the teacher for the given grade in which this pupil is participating and for the subject of this pupil '''
        return Grade.objects.get(id=grade_id).get_subject_teacher(subject_id)
    
    def get_all_teachers(self):
        ''' Retrieves all teachers from this pupil '''
        teachers = []
        for grade in self.get_grades():
            teachers += grade.get_teachers()
            
        return teachers

    def get_grade_teachers(self, grade):
        raise Exception('Not implemented yet')

    def get_audit_skills(self, audit):
        ''' Retrieves all skills evaluated for this pupil '''
        return Skill.objects.select_related().filter(pupilauditskill__pupil=self, pupilauditskill__audit=audit)

    def get_skill_audits(self, skill):
        ''' Retrieves the audits of this pupil in wich the given skill is evaluated '''
        return Audit.objects.select_related().filter(pupilauditskill__pupil=self, pupilauditskill__skill=skill)

    def get_audit_skill_rate(self, audit, skill):
        ''' Retrieves the rating of this pupil for the given skill and given audit '''
        return Skill.objects.select_related().filter(
             pupilauditskill__pupil=self, 
             pupilauditskill__audit=audit, 
             pupilauditskill__skill=skill)

    def __unicode__(self):
        return '%s %s' % (self.first_name, self.last_name)


class Skill(BaseModel):
    ''' Skills are assigned to a subject or other skill '''
    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True, verbose_name='Kompetenzbeschreibung')
    pupil_description = models.TextField(null=True, blank=True, verbose_name='Schülergerechte Übersetzung')
    weight = models.IntegerField(default=0, verbose_name='Gewichtung')
    #TODO: Baumhöhe auf 1 Kind reduzieren!
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children', verbose_name='Unterknoten von')
    
    min_skill_level = models.IntegerField(null=True, blank=True, verbose_name='Geeignet von')
    max_skill_level = models.IntegerField(null=True, blank=True, verbose_name='Geeignet bis')
    
    author = models.ForeignKey(Teacher, null=True, blank=True, verbose_name='Autor')

    class Meta:
        verbose_name = 'Kompetenz'
        verbose_name_plural = 'Kompetenzen'

    def get_audits(self):
        ''' Retrieves all audits evaluated for this skill '''
        return Audit.objects.filter(auditskill__skill=self)

    def __unicode__(self):
        return '%s' % (self.name, )
        
    def get_skill_range(self):
        # check for None explicitely as the skill level can be 0
        if self.is_leaf_node() and self.min_skill_level != None and self.max_skill_level != None:
            return range(self.min_skill_level, self.max_skill_level + 1)
    
    def skill_range_admin(self):
        if self.is_leaf_node():
            if self.min_skill_level and self.max_skill_level:
                return range(self.min_skill_level, self.max_skill_level + 1)
            else:
                return 'nicht angegeben'
        else:
            return ''
    skill_range_admin.short_description = "Schwierigkeitsgrad"
    
    def augment_skill_level_attrs(self, ta):
        rs = self.get_skill_range()
        rta = ta.get_skill_range()
        if rs and rta:        
            if rta[0] in rs or rta[-1] in rs:
                tag = '<span class="skill-ok">%s</span>' 
            elif rta[0] > rs[-1]:
                tag = '<span class="skill-beginner">%s</span>'
            elif rta[0] < rs[0]:
                tag = '<span class="skill-pro">%s</span>' 
        else:
            tag = '<span class="skill-ok">%s</span>' 
        
        self.skill_tag = mark_safe(tag % escape(self.name))
            

features/gsaudit/templates/gsaudit/audit/calendar_helper.html
<div id="calendar" "></div>

<script type='text/javascript'>
	$(document).ready(function() {
        var add_data_partial = function() {        
            // add data-partial attr to all calendar links
            $('#calendar a.fc-event').attr('data-partial', 'gs_content')
        }

        var audits = {{events|safe}};
       
		$('#calendar').fullCalendar({
			events: audits,
			aspectRatio: 2.5,
            firstDay: 1,
            monthNames: ['Januar','Februar','März','April','Mai','Juni','Juli','August','September','Oktober','November','Dezember'],
            monthNamesShort: ['Jan','Feb','Mär','Apr','Mai','Jun','Jul','Aug','Sep','Okt','Nov','Dez'],
            dayNames: ['Sonntag','Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag'],
            dayNamesShort: ['So','Mo','Di','Mi','Do','Fr','Sa'],
            buttonText: {
                prev: '&nbsp;&#9668;&nbsp;',
                next: '&nbsp;&#9658;&nbsp;',
                prevYear: '&nbsp;&lt;&lt;&nbsp;',
                nextYear: '&nbsp;&gt;&gt;&nbsp;',
                today: 'heute',
                month: 'Monat',
                week: 'Woche',
                day: 'tag'
            },
            viewDisplay: function(view) {
                add_data_partial()  
            },
            eventRender: function(event, element) {
                if (event.written_exam)
                    element.addClass('written-exam')
            }
		});
	});
</script>

features/gsaudit/templates/gsaudit/audit/calendar_listing.html
{% extends "gsaudit/audit/frame.html" %}


{% block audit_content %}

    
    {{calendar.render}}
{% endblock %}

features/gsaudit/templates/gsaudit/audit/delete.html
{% extends "gsaudit/audit/frame.html" %}


{% block audit_content %}
    

    <h1> Wollen Sie die Beobachtung <span style="font-weight:bold;">{{ audit.name }} vom {{ audit.date|date:"l d M Y" }}</span> tatsächlich löschen?</h1>
    
    <form method="post">
        {% csrf_token %}
        <div class="buttons mega">
            <input class="deletelink" type="submit" value="JA, Löschen"/>
            <a class="abbrechen" href="{% url "audit-listing" grade_id=grade.id subject_id=subject.id %}">Nein, abbrechen</a>
        </div>
    </div>
    

        
    
{% endblock %}

features/gsaudit/templates/gsaudit/audit/evaluate.html
{% extends "gsaudit/audit/frame.html" %}
{% load i18n %}


{% block course_content %}

    <style>
        .scroll-table-container {height:600px; width:100%;}
        #evaluation-form .submit-row {padding:12px;  margin-top:2px; background:#f5f5f5;}
    </style>
    
    <h1> {{ audit.name }} | {{ audit.date|date:"l, j. F Y" }}</h1>
    {% include "gsaudit/skill_legend.html" %}
    
    <br/>
    
    <form method="post" action="{% url "audit-evaluate" audit_id=audit.id %}" id="evaluation-form">
         <div class="submit-row buttons">
            <input type="submit" name="submit" value="Evaluation speichern"  />
              <a href="{% url "audit-manage" audit_id=audit.id grade_id=audit.assignment.grade.id subject_id=audit.assignment.subject.id %}">Bearbeiten</a>
        </div>
        <div>
            {% csrf_token %}
            <div class="scroll-table-container">
                {{ eval_form.render }}
            </div>
            <div class="submit-row">
                <input type="submit" name="submit" value="Evaluation speichern"  />
            </div>
        </div>
      
    </form>
   

<script type="text/javascript">
$(document).ready(function() {
    var form = $('table.eval-form')
    
    /* apply fixed header table
    -------------------------------------------------------------- */
    form.fixedHeaderTable({fixedColumn:true})
    
    /* work around firefox issue */
      $('.fht-table-init').find('.eval-form-ratings').remove()
    
    /* apply eval notes
    -------------------------------------------------------------- */
    

    var eval_tools = form.find('.skill-tools')
    
    var color_note_link = function(textarea, note_link) {
        // apply trigger higlighting
        if (textarea.val().trim() == '') {
            note_link.css('color', '#888')
        } else {
            note_link.css({'color':'green', 'opacity': 1})           
        }
    }
    
    eval_tools.each(function(index, container) {
        container = $(container)
        var textarea = container.find('textarea')
        var trigger = container.find('.eval-note')
        var diagnosis = container.find('.eval-diagnosis')

        color_note_link(textarea, trigger)        
        
        trigger.click(function() {
            var d = schnipp.ui.Dialog().init()
            
            var dialog_content = $('\
                <div>\
                    <h2></h2>\
                    <textarea></textarea>\
                    <div class="buttons"><a href="#">Übernehmnen</a></div>\
                </div>\
            ')
            var h2 = dialog_content.find('h2')
            h2.html(trigger.attr('data-skill-name'))
            var t = dialog_content.find('textarea')
            t.val(textarea.val())
            var save = dialog_content.find('.buttons a')
            save.click(function() {
                textarea.val(t.val())
                d.close()
                color_note_link(textarea, trigger)
                return false
            })
            
            d.set_content(dialog_content)
            d.set_title(trigger.attr('data-pupil-name'))
            d.show()
        })
        
        
    })
    
    
    form.find('.eval-note').click(function() {
        
    })
    
    
    
    

})
</script>

{% endblock %}

features/gsaudit/templates/gsaudit/audit/frame.html
{% extends "gsaudit/course/frame.html" %}



{% block course_content %}
    
    <div class="exam-legend float-right">
       
        <a href="{% url "audit-listing" grade_id=grade.id subject_id=subject.id %}" {% if listing_view %} class="active" {% endif %}>Listen-Ansicht</a> | 
        <a href="{% url "audit-calendar_listing" grade_id=grade.id subject_id=subject.id %}" {% if calendar_listing_view %} class="active" {% endif %}>Kalender-Ansicht</a>
         <br/><br/>
        <div class="oral-exam-legend "><span></span> Beobachtungen</div>
        <div class="written-exam-legend"><span></span> Schriftliche Lernstandserhebungen</div>
    </div>
    <div class="buttons small" id="audit-toolbar">
        <a href="{% url "audit-manage" grade_id=grade.id subject_id=subject.id %}" class="oral-exam">+ Beobachtung anlegen</a>
        <a href="{% url "exam-manage" grade_id=grade.id subject_id=subject.id %}" class="written-exam">+ Schriftliche Lernstandserhebungen anlegen</a>
    </div>
    
    <div id="audit-views"></div>
    
    
    {% block audit_content %} {% endblock %}
    
{% endblock %}

features/gsaudit/templates/gsaudit/audit/listing.html
{% extends "gsaudit/audit/frame.html" %}


{% block audit_content %}
    


        

    
<div class="audit-listing">
    {% if audits %}
        {% for audit in audits %}
            <div class="{% if audit.written_exam %}written-exam {% else %}  oral-exam {% endif %}" >
                <a href="{% url "audit-evaluate" audit_id=audit.id %}" class="audit " >{{ audit.name }} | {{ audit.date|date:"d F Y" }}</a>
                <a href="{% url "audit-delete" audit_id=audit.id %}" class="delete" >&nbsp;</a>
                <a href="{% url "audit-manage" audit_id=audit.id grade_id=audit.assignment.grade.id subject_id=audit.assignment.subject.id %}" class="edit">&nbsp;</a>
                <div class="clear"></div>
            </div>
        {% endfor %}
    {% else %}
        <div class="note">
            Es existieren noch keine Beobachtungen.    
        </div>
    {% endif %}
    
</div>
{% endblock %}

features/gsaudit/templates/gsaudit/audit/manage.html
{% extends "gsaudit/course/frame.html" %}
{% load i18n %}
{% load mptt_tags %}





{% block course_content %}
<style>
    .form-row {padding: 12px 0px 12px 0px; background:#fff; border-bottom:1px solid #eee;
    }
    
    .submit-row {padding: 12px; background:#fbfbfb; border-bottom:1px solid #eee;}
    
    .form-row label {font-size:12px;}
    .form-row.errors {border-color: red; background: #FCF2F2}
    
    .errorlist {font-size:12px; color:red;}
    .errorlist li {margin:0px; padding:0px; }
    

    #audit-form ul li {list-style:none;}
    .pupil-selection ul > li {margin-left:0px;} 
    .pupil-selection label:hover {cursor:pointer;}
    #audit-form-left {float:left; border-right:0px solid #eee; width:30%}
    #audit-form-right {float:left; width:65%; margin-left:33px;border-left:0px solid #fff;}    
    
    .skilltree {font-size:13px; padding:0px;}
    .skilltree-filters a {text-decoration:none; color:#999; font-size:12px; border-right:1px solid #eee;
        border-left:1px solid #fff; float:left; padding: 2px 4px 2px 4px; background:#fff;
    }
    
    .skilltree {margin-top:12px; }
    .skilltree li {list-style:none; margin-left:22px; }
    .skilltree li div.node {padding:5px 0px 5px 0px;  display:block; color:#646464; font-weight:bold;}
    .skilltree li label {display:inline; cursor:pointer;}
    .skilltree > li {margin:0px;}
    .skilltree li.collapsable div.node {cursor:pointer; font-style:normal; font-weight:normal}
    .skilltree li.collapsable div.node:hover {background:#f5f5f5; } 
    .skilltree li.collapsable .children {display:none;}
    
    
    textarea#id_description {height:100px;}
   
    #ui-datepicker-div {background:#fff; padding:3px; border: 1px solid #ccc;}
    .ui-datepicker-calendar td {padding:5px; background:#fff; z-index:3;}
    .ui-datepicker-calendar tbody td a {text-decoration:none; font-size:12px;}
    .ui-datepicker-calendar tbody td {border: 1px solid #eee;}
    .ui-datepicker-calendar th {font-weight:normal; font-size:13px; padding-bottom:4px;}
    .ui-datepicker-title {font-size:13px; background:#eee; padding: 2px 3px 5px 6px; margin-top:3px;}
    .ui-datepicker-header {}
    .ui-datepicker-header a {font-size: 13px; padding: 2px 3px 5px 6px; cursor:pointer;}
    
    #select-all {font-size:12px; cursor:pointer;}
</style>


<div>
    {% if create%}
        <h1>{{ audit.get_type }} anlegen</h1>
    {% else %}
        <h1>{{ audit }} bearbeiten</h1>
    {% endif %}
    
    <form method="post" action="{{ post_url }}" id="audit-form">
            {% csrf_token %}
            <div class="submit-row buttons">
                <input type="submit" value="Speichern" />
                {% if edit_mode %}
                 <a class="current" href="{% url "audit-evaluate" audit_id=audit.id %}">Evaluieren</a>
                 {% endif %}
            </div>
            <div id="audit-form-left">
                <div class="form-row {% if auditform.name.errors %} errors {% endif %}">
                    <p>{{ auditform.name.label_tag }}</p>
                    {{ auditform.name.errors }}
                    {{ auditform.name }}
                </div>
                                
                <div class="form-row {% if auditform.description.errors %} errors {% endif %}">
                    <p>{{ auditform.description.label_tag }}</p>
                    {{ auditform.description.errors }}
                    <div style="">
                        {{ auditform.description }}
                    </div>
                </div>
                <div class="form-row pupil-selection {% if auditform.pupils.errors %} errors {% endif %}">
                    <p>
                        <label>
                            {{ auditform.pupils.label }}
                            <a id="select-all">[ Alle wählen ]</a>
                        </label>
                    </p>
                    {{ auditform.pupils.errors }}
                    {{ auditform.pupils }}
                </div>
            </div>
            <div id="audit-form-right">
                
                <div style="border-left:1px solid #fff;">
                     <div class="form-row {% if auditform.date.errors %} errors {% endif %}">
                    <p>{{ auditform.date.label_tag }}</p>
                    {{auditform.date.errors}}
                    {{ auditform.date }}
                </div>   
                    <div class="form-row {% if auditform.errors.skills %} errors {% endif %}" style="padding-left:22px; border-left:1px solid #eee;">
                        {% if auditform.errors.skills %}
                        <div class="errorlist">{{ auditform.errors.skills }}</div>
                        {% endif %}
                        
                        <h2>Kompetenzen auswählen</h2>
                        {% include "gsaudit/skill_legend.html" %}
                        
                       
                        <ul class="skilltree">
                            {% recursetree skills %}
                                <li >
                                    <div class=" node {% if node.is_leaf_node %} leaf {% endif %} ">
                                        {% if node.is_leaf_node %}<input id="skill-{{node.id}}" type="checkbox" name="selected_skills" {{ node.selected }} value="{{node.id}}"/>{% endif %}
                                        {% if node.is_leaf_node %}<label for="skill-{{node.id}}" title="{{ node.description }}"> {{ node.skill_tag }}</label> {% else %}
                                            {{ node.name }}
                                        {% endif %}
                                    </div>
                                    {% if not node.is_leaf_node %}
                                        <ul class="children">
                                            {{ children }}
                                        </ul>
                                    {% endif %}
                                </li>
                            {% endrecursetree %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="clear"></div>
                <div class="submit-row buttons">
                <input type="submit" value="Speichern" />
                {% if edit_mode %}
                 <a class="current" href="{% url "audit-evaluate" audit_id=audit.id %}">Evaluieren</a>
                 {% endif %}
            </div>
                
        <script>
        
        /*
        var form_count = {{ formset.total_form_count }};
        $('#add_form').click(function() {
            form_count++;
            var form = '{{formset.default_form.as_p|escapejs}}'.replace(/__prefix__/g, form_count);
            form = $('<div class="inline">' + form + '<div style="clear:both"></div></div>').hide();
            $('#forms').append(form);
            form.fadeIn('slow');
            $('#id_form-TOTAL_FORMS').val(form_count);
            return false;
        });*/
        
        $('#id_date').datepicker({dateFormat: 'dd.mm.yy'});

        $('#select-all').click(function() {
            $('.pupil-selection input[type="checkbox"]').attr('checked', 'True')
        })
    

        $('.skilltree .node.leaf').each(function() {
            var li = $(this).parent().parent().closest('li')
            li.addClass('collapsable')  
        })
        
        $('.skilltree .collapsable > div').each(function(index, elem) {
            elem = $(elem)
            elem.text('+' + elem.text())
        })
     
        
        
        $('.collapsable > div').click(function() {
            var children = $(this).parent().children('.children')
        
            if (children.css('display') == 'none')
                children.show('blind')
                
            else
                children.hide('blind')
        })
        //console.log($('input[type="checkbox"]:checked').closest('ul'))
        $('input[type="checkbox"]:checked').parentsUntil('ul.skilltree').show()
        
        
        </script>
    </form>
</div>
{% endblock %}


<div id="forms">
    {% for form in formset %}
    <div class="inline">
        {{ form.as_p }}
    </div>
    {% endfor %}
</div>
<div class="inline">
    <div class="object-tools mini">
        <a href="#" id="add_form" class="addlink">Weitere Kompetenz hinzufügen</a>
    </div>
    <input type="submit" name="submit" value="speichern" style="float:right" />
</div>